/* Reusable PayPal Orders v2 sandbox adapter. Live endpoints are intentionally absent. */
export const PAYPAL_BASE='https://api-m.sandbox.paypal.com';
export const DEMO_CATALOG=Object.freeze({demo_one:{name:'T-shirt Studio · Demo',value:'1.00',currency:'EUR'},demo_five:{name:'Felpa Club · Demo',value:'5.00',currency:'EUR'}});
export function cartQuote(input){
 if(typeof input==='string'){if(!Object.hasOwn(DEMO_CATALOG,input))throw new PayPalError('Articolo non valido.',400,'INVALID_PRODUCT');return {...DEMO_CATALOG[input],reference:input,selection:input}}
 if(!Array.isArray(input)||!input.length||input.length>10)throw new PayPalError('Il carrello è vuoto o non valido.',400,'INVALID_CART');
 const seen=new Set();let cents=0;const selection=input.map(row=>{if(!row||!Object.hasOwn(DEMO_CATALOG,row.id)||!Number.isInteger(row.quantity)||row.quantity<1||row.quantity>10||seen.has(row.id))throw new PayPalError('Articolo o quantità non validi.',400,'INVALID_CART');seen.add(row.id);cents+=Math.round(Number(DEMO_CATALOG[row.id].value)*100)*row.quantity;return {id:row.id,quantity:row.quantity}}).sort((a,b)=>a.id.localeCompare(b.id));
 return {name:'Carrello dimostrativo',value:(cents/100).toFixed(2),currency:'EUR',reference:'cart',selection};
}
export function configured(env){return !!(env.PAYPAL_SANDBOX_CLIENT_ID&&env.PAYPAL_SANDBOX_CLIENT_SECRET)}
export class PayPalError extends Error{constructor(message,status=502,code='PAYPAL_ERROR'){super(message);this.status=status;this.code=code}}
const encoder=new TextEncoder();
function base64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function decode64(text){const s=text.replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(s+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0))}
async function signingKey(secret){return crypto.subtle.importKey('raw',encoder.encode('dv-paypal-sandbox-ticket-v1:'+secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
export async function issueTicket(payload,secret){const content=base64url(encoder.encode(JSON.stringify(payload))),key=await signingKey(secret);return content+'.'+base64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(content))))}
export async function verifyTicket(ticket,secret,origin){try{if(typeof ticket!=='string'||ticket.length>3000)throw Error();const [content,signature,extra]=ticket.split('.');if(extra||!content||!signature)throw Error();const key=await signingKey(secret);if(!await crypto.subtle.verify('HMAC',key,decode64(signature),encoder.encode(content)))throw Error();const payload=JSON.parse(new TextDecoder().decode(decode64(content)));if(payload.origin!==origin||!Number.isFinite(payload.exp)||payload.exp<Date.now()||!/^\w{8,32}$/.test(payload.orderId))throw Error();cartQuote(payload.product);return payload}catch{throw new PayPalError('Sessione di test scaduta o non valida. Crea un nuovo ordine.',403,'INVALID_TICKET')}}
export async function requestId(value){const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value)));return [...hash].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32)}
async function json(response){return response.json().catch(()=>({}))}
export async function paypalToken(env){if(!configured(env))throw new PayPalError('Configura le credenziali PayPal Sandbox su Cloudflare.',503,'NOT_CONFIGURED');let response;try{response=await fetch(PAYPAL_BASE+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+btoa(env.PAYPAL_SANDBOX_CLIENT_ID+':'+env.PAYPAL_SANDBOX_CLIENT_SECRET),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',signal:AbortSignal.timeout(15000)})}catch{throw new PayPalError('PayPal Sandbox non risponde. Riprova tra poco.',502,'UPSTREAM_UNAVAILABLE')}const data=await json(response);if(!response.ok||!data.access_token)throw new PayPalError('PayPal Sandbox non accetta le credenziali configurate. Controlla che siano Sandbox.',503,'CREDENTIALS_REJECTED');return data.access_token}
export async function paypalRequest(token,path,method='GET',body,idem){let response;try{response=await fetch(PAYPAL_BASE+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'return=representation',...(idem?{'PayPal-Request-Id':idem}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)})}catch{throw new PayPalError('Risposta PayPal non ricevuta. Verifica lo stato dell’ordine prima di ripetere il test.',502,'UNCERTAIN_RESULT')}const data=await json(response);if(!response.ok){const issue=data.details?.[0]?.issue;if(issue==='INSTRUMENT_DECLINED')throw new PayPalError('Il conto di prova non ha autorizzato il pagamento. Riprova dal checkout.',422,'INSTRUMENT_DECLINED');if(issue==='ORDER_NOT_APPROVED')throw new PayPalError('Approva prima l’ordine nella finestra PayPal Sandbox.',409,'ORDER_NOT_APPROVED');throw new PayPalError('PayPal Sandbox non ha completato la richiesta. Verifica lo stato dell’ordine o riprova.',502,'PAYPAL_REJECTED')}return data}
export function validateOrder(order,product,orderId){const item=cartQuote(product),units=order.purchase_units;if(!item||order.id!==orderId||!Array.isArray(units)||units.length!==1||units[0].reference_id!==item.reference||units[0].amount?.currency_code!==item.currency||units[0].amount?.value!==item.value)throw new PayPalError('I dettagli dell’ordine non corrispondono al test creato.',409,'ORDER_MISMATCH');return units[0]}
export function orderSummary(order,product,orderId){const quote=cartQuote(product),unit=validateOrder(order,product,orderId),captures=unit.payments?.captures||[],capture=captures[0];const completed=order.status==='COMPLETED'&&captures.length===1&&capture.status==='COMPLETED'&&capture.amount?.currency_code===quote.currency&&capture.amount?.value===quote.value;return {environment:'sandbox',orderId,status:completed?'COMPLETED':order.status==='COMPLETED'?'UNVERIFIED':capture?.status||order.status||'UNKNOWN',completed,captureId:completed?capture.id:null,amount:quote.value,currency:quote.currency,product,checkedAt:new Date().toISOString()}}
export function safeError(error){return Response.json({error:error instanceof PayPalError?error.message:'Operazione non riuscita. Riprova.',code:error instanceof PayPalError?error.code:'INTERNAL_ERROR',environment:'sandbox'},{status:error instanceof PayPalError?error.status:500,headers:{'Cache-Control':'no-store'}})}
