/* Presentation only: all account and data services remain in their original modules. */
(() => {
 const auth=document.getElementById('authOverlay');
 const reduced=()=>matchMedia('(prefers-reduced-motion:reduce)').matches||document.body.classList.contains('motion-paused');
 const intro=document.createElement('dialog');intro.className='cinema-dialog';intro.setAttribute('aria-label','Benvenuto in DV SPACE');
 intro.classList.add('product-film');
 intro.innerHTML='<div class="cinema-top"><span>DV / SPACE</span><button class="cinema-close" autofocus>Salta intro ↗</button></div><div class="film-stage" aria-hidden="true"><div class="film-light"></div><div class="film-halo"></div><div class="film-ray"></div><img class="film-sculpture" src="assets/art/chrome-loop.png" alt=""><div class="film-vignette"></div><div class="film-copy film-one"><span class="film-caption">OGNI MOMENTO CONTA.</span><strong>Il tuo tempo.</strong></div><div class="film-copy film-two"><span class="film-caption">SENZA CONFINI.</span><strong>Le tue idee.</strong></div><div class="film-copy film-three"><strong>Un universo.<br><em>Il tuo.</em></strong></div><div class="film-copy film-end"><span class="film-signature"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none"><path d="M76 24C63 11 40 12 25 27C9 43 10 66 24 78" stroke="currentColor" stroke-width="9" stroke-linecap="round"/><path d="M24 76C37 89 60 88 75 73C91 57 90 34 76 22" stroke="currentColor" stroke-width="9" stroke-linecap="round"/><path d="M23 72L72 23" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><circle cx="77" cy="18" r="8" fill="currentColor"/></svg></span><span class="film-wordmark">SPACE</span><p>Fai spazio a ciò che sei.</p><span class="film-edition">PERSONAL UNIVERSE — DESIGNED AROUND YOU</span></div><div class="film-footer"><span>DAVIDE VILLANO</span><span>IL TUO SPAZIO. UNA NUOVA PROSPETTIVA.</span></div><div class="film-progress"></div></div><p class="film-accessible">DV SPACE. Il tuo tempo. Le tue idee. Un universo. Il tuo.</p>';
 document.body.append(intro);
 let introTimer;let closing=false;
 function rememberIntro(){try{sessionStorage.setItem('dv-orbit-film-v8','seen')}catch(_){}}
 function finishIntro(){clearTimeout(introTimer);if(!intro.open||closing)return;closing=true;rememberIntro();const close=()=>{if(intro.open)intro.close();intro.classList.remove('film-playing','film-still');closing=false};if(reduced()||!intro.animate){close();return}intro.animate([{opacity:1},{opacity:0}],{duration:350,easing:'ease-out'}).finished.then(close,close)}
 function playIntro(){clearTimeout(introTimer);closing=false;intro.classList.remove('film-playing','film-still');intro.showModal();void intro.offsetWidth;intro.classList.add(reduced()?'film-still':'film-playing');introTimer=setTimeout(finishIntro,reduced()?3000:12500)}
 intro.querySelector('button').onclick=finishIntro;intro.addEventListener('cancel',e=>{e.preventDefault();finishIntro()});
 let seen=false;try{seen=sessionStorage.getItem('dv-orbit-film-v8')==='seen'}catch(_){}
 // Never delay email confirmation, recovery or reduced-motion entry.
 if(!seen&&!reduced()&&!location.hash&&!location.search)playIntro();
 matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',()=>{if(reduced())finishIntro()});
 const menu=document.createElement('dialog');menu.className='cinema-dialog';menu.setAttribute('aria-labelledby','cinemaMenuTitle');
 menu.innerHTML='<div class="cinema-top"><span>DV / SPACE — ESPLORA</span><button class="cinema-close" autofocus>Chiudi ×</button></div><div class="menu-layout"><div class="menu-art"><span class="menu-chapter">COLLEZIONE PERSONALE / 06</span><h2 id="cinemaMenuTitle">Scegli la tua<br><em>prossima orbita.</em></h2><p id="cinemaPreview">Uno spazio per ogni parte di te. Scegli da dove ripartire.</p></div><nav class="cinema-links" aria-label="Esplora le sezioni"></nav></div>';
 document.body.append(menu);
 const descriptions={home:'Il tuo oggi, a colpo d’occhio.',calendario:'Fai spazio ai momenti che contano.',percorso:'Ogni passo racconta la tua storia.',contatti:'Le persone, sempre a portata di mano.',wishlist:'Dai un posto ai tuoi prossimi desideri.',spese:'Più chiarezza nelle scelte di ogni giorno.',esperimenti:'Segui la curiosità. Scopri qualcosa di nuovo.'};
 const toggle=document.getElementById('navToggle');toggle.setAttribute('aria-controls','cinemaMenu');menu.id='cinemaMenu';
 function closeMenu(){if(menu.open)menu.close();toggle.setAttribute('aria-expanded','false')}
 menu.querySelector('.cinema-close').onclick=closeMenu;menu.addEventListener('cancel',e=>{e.preventDefault();closeMenu()});menu.addEventListener('close',()=>toggle.setAttribute('aria-expanded','false'));
 document.querySelectorAll('.tab-btn').forEach((tab,i)=>{const button=document.createElement('button');button.className='cinema-link';button.type='button';button.dataset.section=tab.dataset.module;button.style.setProperty('--i',i);const num=document.createElement('small');num.textContent=String(i).padStart(2,'0');const label=document.createElement('strong');label.textContent=tab.querySelector('span').textContent;const arrow=document.createElement('span');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');button.append(num,label,arrow);const preview=()=>{menu.querySelector('#cinemaPreview').textContent=descriptions[tab.dataset.module]};button.onpointerenter=preview;button.onfocus=preview;button.onclick=()=>{closeMenu();showModule(tab.dataset.module,{transition:true});setTimeout(()=>document.getElementById('mod-'+tab.dataset.module).focus({preventScroll:true}),750)};menu.querySelector('nav').append(button)});
 addEventListener('director:menu',()=>{if(!auth.classList.contains('hidden'))return;menu.querySelectorAll('[data-section]').forEach(b=>{if(document.getElementById('mod-'+b.dataset.section).classList.contains('active'))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});menu.showModal();toggle.setAttribute('aria-expanded','true')});
 new MutationObserver(()=>{if(!auth.classList.contains('hidden'))closeMenu()}).observe(auth,{attributes:true,attributeFilter:['class']});
 const utility=document.createElement('div');utility.className='cinema-utilities';
 for(const [label,id] of [['Un momento di focus','sidebarFocus'],['Esci dall’account','logoutBtn']]){const b=document.createElement('button');b.className='cinema-close';b.type='button';b.textContent=label;b.onclick=()=>{closeMenu();document.getElementById(id).click()};utility.append(b)}
 const replayMenu=document.createElement('button');replayMenu.className='cinema-close';replayMenu.textContent='Rivedi intro';replayMenu.onclick=()=>{closeMenu();playIntro()};utility.append(replayMenu);menu.querySelector('nav').append(utility);
 const replay=document.createElement('button');replay.type='button';replay.className='sidebar-focus';replay.textContent='↻ Rivedi l’intro';replay.onclick=()=>{playIntro()};document.querySelector('.sidebar-bottom').prepend(replay);
 addEventListener('space:motion',()=>{if(reduced())finishIntro()});
})();
