/* Presentation only: all account and data services remain in their original modules. */
(() => {
 const auth=document.getElementById('authOverlay');
 const reduced=()=>matchMedia('(prefers-reduced-motion:reduce)').matches||document.body.classList.contains('motion-paused');
 const intro=document.createElement('dialog');intro.className='cinema-dialog';intro.setAttribute('aria-label','Benvenuto in DV SPACE');
 intro.classList.add('product-film','runway-premiere');
 intro.innerHTML=`<div class="cinema-top"><span class="cinema-brand">DV / THE RUNWAY</span><button type="button" class="cinema-close" autofocus>Salta intro ↗</button></div><div class="runway-stage" aria-hidden="true"><div id="introRunwayHost" class="runway-canvas-host"></div><div class="show-curtain show-curtain-left"></div><div class="show-curtain show-curtain-right"></div><video class="runway-video" muted playsinline preload="none" poster="assets/editorial/runway.jpg" data-src="assets/editorial/fashion-film.mp4"></video><div class="runway-shade"></div><div class="runway-copy runway-one"><small>PLEASE TAKE YOUR SEAT</small><strong>The show<br><em>is yours.</em></strong></div><div class="runway-copy runway-two"><small>LIGHTS. SILHOUETTES. YOU.</small><strong>Beyond<br><em>the front row.</em></strong></div><div class="runway-copy runway-end"><small>DAVIDE VILLANO / COLLECTION 2026</small><strong>SPACE<span>the runway</span></strong></div><div class="runway-footer"><span>STYLE IS A WAY OF LIFE.</span><span>VOL. 09</span></div><div class="runway-progress"></div></div>`;
 document.body.append(intro);
 let introTimer;let closing=false;
 function rememberIntro(){try{sessionStorage.setItem('dv-runway-live-v10','seen')}catch(_){}}
 function finishIntro(){clearTimeout(introTimer);if(!intro.open||closing)return;closing=true;rememberIntro();const close=()=>{if(intro.open)intro.close();intro.classList.remove('film-playing','film-still');intro.querySelector('video').pause();closing=false};if(reduced()||!intro.animate){close();return}intro.animate([{opacity:1},{opacity:0}],{duration:350,easing:'ease-out'}).finished.then(close,close)}
 function playIntro(){clearTimeout(introTimer);closing=false;intro.classList.remove('film-playing','film-still');intro.showModal();const video=intro.querySelector('video');if(!reduced()){if(!video.getAttribute('src'))video.src=video.dataset.src;video.currentTime=0;video.play().catch(()=>{});}void intro.offsetWidth;intro.classList.add(reduced()?'film-still':'film-playing');introTimer=setTimeout(finishIntro,reduced()?3000:10500)}
 intro.querySelector('button').onclick=finishIntro;intro.addEventListener('cancel',e=>{e.preventDefault();finishIntro()});
 let seen=false;try{seen=sessionStorage.getItem('dv-runway-live-v10')==='seen'}catch(_){}
 // Never delay email confirmation, recovery or reduced-motion entry.
 if(!seen&&!reduced()&&!location.hash&&!location.search)playIntro();
 matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',()=>{if(reduced())finishIntro()});
 const menu=document.createElement('dialog');menu.className='cinema-dialog';menu.setAttribute('aria-labelledby','cinemaMenuTitle');
 menu.innerHTML='<div class="cinema-top"><span class="cinema-brand"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none"><path d="M76 24C63 11 40 12 25 27C9 43 10 66 24 78" stroke="currentColor" stroke-width="9" stroke-linecap="round"/><path d="M24 76C37 89 60 88 75 73C91 57 90 34 76 22" stroke="currentColor" stroke-width="9" stroke-linecap="round"/><path d="M23 72L72 23" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><circle cx="77" cy="18" r="8" fill="currentColor"/></svg><span>SPACE — ESPLORA</span></span><button class="cinema-close" autofocus>Chiudi ×</button></div><div class="menu-layout"><div class="menu-art"><span class="menu-chapter">INDICE / LA TUA COLLEZIONE</span><h2 id="cinemaMenuTitle">Ogni giorno,<br><em>un capitolo.</em></h2><p id="cinemaPreview">Il tempo, le persone, i desideri. Sfoglia il tuo mondo.</p></div><nav class="cinema-links" aria-label="Esplora le sezioni"></nav></div>';
 document.body.append(menu);
 const descriptions={home:'Il tuo oggi, a colpo d’occhio.',calendario:'Fai spazio ai momenti che contano.',percorso:'Ogni passo racconta la tua storia.',contatti:'Le persone, sempre a portata di mano.',wishlist:'Dai un posto ai tuoi prossimi desideri.',spese:'Più chiarezza nelle scelte di ogni giorno.',esperimenti:'Segui la curiosità. Scopri qualcosa di nuovo.'};
 const toggle=document.getElementById('navToggle');toggle.setAttribute('aria-controls','cinemaMenu');menu.id='cinemaMenu';
 function closeMenu(){if(menu.open)menu.close();toggle.setAttribute('aria-expanded','false')}
 menu.querySelector('.cinema-close').onclick=closeMenu;menu.addEventListener('cancel',e=>{e.preventDefault();closeMenu()});menu.addEventListener('close',()=>toggle.setAttribute('aria-expanded','false'));
 document.querySelectorAll('.tab-btn').forEach((tab,i)=>{const button=document.createElement('button');button.className='cinema-link';button.type='button';button.dataset.section=tab.dataset.module;button.style.setProperty('--i',i);const num=document.createElement('small');num.textContent=String(i).padStart(2,'0');const label=document.createElement('strong');label.textContent=tab.querySelector('span').textContent;const arrow=document.createElement('span');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');button.append(num,label,arrow);const preview=()=>{menu.querySelector('#cinemaPreview').textContent=descriptions[tab.dataset.module]};button.onpointerenter=preview;button.onfocus=preview;button.onclick=()=>{closeMenu();showModule(tab.dataset.module,{transition:true});setTimeout(()=>document.getElementById('mod-'+tab.dataset.module).focus({preventScroll:true}),750)};menu.querySelector('nav').append(button)});
 addEventListener('director:menu',()=>{if(!auth.classList.contains('hidden'))return;menu.querySelectorAll('[data-section]').forEach(b=>{if(document.getElementById('mod-'+b.dataset.section).classList.contains('active'))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});menu.showModal();toggle.setAttribute('aria-expanded','true')});
 new MutationObserver(()=>{if(!auth.classList.contains('hidden'))closeMenu()}).observe(auth,{attributes:true,attributeFilter:['class']});
 const utility=document.createElement('div');utility.className='cinema-utilities';
 for(const [label,id] of [['Un momento di focus','sidebarFocus'],['Esci dall’account','logoutBtn']]){const b=document.createElement('button');b.className='cinema-close';b.type='button';b.textContent=label;b.onclick=()=>{closeMenu();document.getElementById(id).click()};utility.append(b)}
 const replayMenu=document.createElement('button');replayMenu.className='cinema-close';replayMenu.textContent='Rivedi intro';replayMenu.onclick=()=>{closeMenu();playIntro()};utility.append(replayMenu);menu.querySelector('nav').append(utility);
 const replay=document.createElement('button');replay.type='button';replay.className='sidebar-focus';replay.textContent='↻ Rivedi l’intro';replay.onclick=()=>{playIntro()};document.querySelector('.sidebar-bottom').prepend(replay);
 addEventListener('space:motion',()=>{if(reduced())finishIntro()});
})();
