/* The personal front row: data stays in the existing user-owned workspace. */
(()=>{
 const home=document.getElementById('mod-home');
 const edition=document.createElement('section');edition.className='personal-edition';edition.setAttribute('aria-label','La mia edizione');
 edition.innerHTML=`<div class="edition-topline"><span>DV / FASHION WEEK EDITION</span><span>IL TUO ACCESSO PERSONALE</span></div><div class="edition-cover"><div class="edition-copy"><span class="eyebrow">THE FRONT ROW IS YOURS</span><h2>La tua vita.<br><em>La tua sfilata.</em></h2><p id="editionSignature">Una selezione di ciò che ami. Uno spazio che parla di te.</p><div class="edition-actions"><button type="button" id="editionRunway">Entra in passerella ↗</button><button type="button" id="editionCustomize">Il mio profilo</button></div></div><aside class="edition-pass" data-avatar="monogram"><span>DV / ACCESS PASS</span><div id="editionAvatar" aria-hidden="true">DV</div><strong id="editionName">La mia edizione</strong><p>PERSONAL COLLECTION</p><div class="pass-stripes" aria-hidden="true"></div><span>YOUR STYLE. YOUR RULES.</span></aside></div><div class="edition-digest"><button type="button" data-open="calendario"><span>01 / NEXT ON THE AGENDA</span><strong id="editionNext">Il tuo prossimo appuntamento</strong><small id="editionWhen">Apri il calendario ↗</small></button><button type="button" data-open="wishlist"><span>02 / THE WISHLIST</span><strong id="editionWishes">La tua selezione</strong><small>Desideri, dettagli, pezzi del cuore ↗</small></button><button type="button" data-open="spese"><span>03 / THIS MONTH</span><strong id="editionBudget">Le tue spese</strong><small>Il valore delle tue scelte ↗</small></button></div>`;
 home.prepend(edition);
 const passions=document.createElement('div');passions.className='edition-actions';for(const [id,label] of [['calcio','Bologna & Napoli ↗']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>showModule(id,{transition:true});passions.append(b)}edition.append(passions);
 edition.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showModule(b.dataset.open,{transition:true}));
 document.getElementById('editionCustomize').onclick=()=>document.querySelector('.sidebar-bottom .sidebar-focus').click();
 document.getElementById('editionRunway').onclick=()=>document.querySelector('.runway-tour').scrollIntoView({behavior:document.body.classList.contains('motion-paused')?'instant':'smooth'});
 function update(){const user=typeof currentUser!=='undefined'?currentUser:null;const p=normalizedPreferences(user?.user_metadata?.workspace_preferences);const name=user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'La mia edizione';document.getElementById('editionName').textContent=name;document.getElementById('editionAvatar').textContent=name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();document.querySelector('.edition-pass').dataset.avatar=p.avatar;document.getElementById('editionSignature').textContent=p.bio||'Una selezione di ciò che ami. Uno spazio che parla di te.';home.classList.toggle('edition-essentials',p.sections==='essentials');document.getElementById('editionRunway').hidden=p.sections==='essentials';document.getElementById('editionNext').textContent=document.getElementById('nextEventTitle').textContent;document.getElementById('editionWhen').textContent=document.getElementById('nextEventDate').textContent;document.getElementById('editionWishes').textContent=(document.getElementById('wlCountAll').textContent||'0')+' pezzi selezionati';document.getElementById('editionBudget').textContent=fmtEuro(expenseEntries.filter(x=>String(x.expense_date).slice(0,7)===localCalendarDate().slice(0,7)).reduce((sum,x)=>sum+expenseCents(x.amount),0)/100);}
 for(const id of ['nextEventTitle','nextEventDate','wlCountAll','spMonthTotal','sidebarName'])new MutationObserver(update).observe(document.getElementById(id),{childList:true,subtree:true,characterData:true});
 addEventListener('personal:appearance',update);addEventListener('workspace:module',update);update();
 const filters=document.createElement('div');filters.className='wish-filters';filters.innerHTML='<label>Cerca nella selezione<input id="wishSearch" type="search" placeholder="Nome, brand, colore…" autocomplete="off"></label><label>Mostra<select id="wishFilter"><option value="all">Tutti i pezzi</option><option value="waiting">Da acquistare</option><option value="purchased">Acquistati</option><option value="high">Priorità alta</option></select></label>';document.getElementById('wlGrid').before(filters);filters.addEventListener('input',renderWishlist);filters.addEventListener('change',renderWishlist);
 new MutationObserver(()=>{if(!document.getElementById('authOverlay').classList.contains('hidden')){document.getElementById('wishSearch').value='';document.getElementById('wishFilter').value='all'}}).observe(document.getElementById('authOverlay'),{attributes:true,attributeFilter:['class']});
 // Owner contacts are configured in source, never read from a visitor's private address book.
 const contact=document.createElement('dialog');contact.className='personal-settings owner-contact';contact.setAttribute('aria-labelledby','ownerContactTitle');contact.innerHTML='<div class="personal-settings-head"><span class="eyebrow">DV / GET IN TOUCH</span><button type="button" aria-label="Chiudi contatti">×</button></div><h2 id="ownerContactTitle">Contatta Davide.</h2><p>Idee, progetti, collaborazioni.</p><div class="owner-contact-links"></div>';contact.querySelector('button').onclick=()=>contact.close();document.body.append(contact);
 const config=window.DV_PUBLIC_CONTACT||{},links=contact.querySelector('.owner-contact-links');
 for(const [label,value,kind] of [['Email',config.email,'email'],['Instagram',config.instagram,'url'],['Portfolio',config.website,'url']]){if(!value)continue;const a=document.createElement('a');if(kind==='email'){if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(value))continue;a.href='mailto:'+value}else{const safe=safeWebUrl(value);if(!safe)continue;a.href=safe;a.target='_blank';a.rel='noopener noreferrer'}a.textContent=label+' ↗';links.append(a)}
 if(!links.children.length)links.textContent='I recapiti pubblici saranno disponibili qui.';
 for(const target of [document.querySelector('.sidebar-bottom'),document.querySelector('.cinema-utilities'),document.querySelector('.auth-form-side')]){if(!target)continue;const b=document.createElement('button');b.type='button';b.className='owner-contact-trigger';b.textContent='Contatta Davide ↗';b.onclick=()=>{document.getElementById('cinemaMenu')?.close();contact.showModal()};target.append(b)}
})();

/* Removal waits eight seconds. Undo, logout or leaving the page cancels it. */
function confirmWishlistRemoval(item){if(confirmWishlistRemoval.pending)return Promise.resolve(false);confirmWishlistRemoval.pending=true;return new Promise(resolve=>{
 const owner=currentUser?.id,bar=document.createElement('div');bar.className='wish-undo';bar.setAttribute('role','status');const text=document.createElement('span');text.textContent='Rimozione programmata: '+(item.title||'prodotto');const undo=document.createElement('button');undo.type='button';undo.textContent='Annulla';bar.append(text,undo);document.body.append(bar);
 let timer;const auth=document.getElementById('authOverlay');const observer=new MutationObserver(()=>{if(!auth.classList.contains('hidden'))finish(false)});const leave=()=>finish(false);
 function finish(ok){confirmWishlistRemoval.pending=false;clearTimeout(timer);observer.disconnect();removeEventListener('pagehide',leave);bar.remove();resolve(ok&&currentUser?.id===owner&&!!owner)}
 undo.onclick=()=>finish(false);observer.observe(auth,{attributes:true,attributeFilter:['class']});addEventListener('pagehide',leave,{once:true});timer=setTimeout(()=>finish(true),8000);
})}
