// The gallery is a visual layer; personal data and authentication stay in the original modules.
export function createMuseum(THREE,{scene,group,globe,orbit,chrome,accent,camera,renderStill,overlay,holders}){
 const rooms=[['home','Orbita terrestre','Il punto da cui tutto comincia.'],['calendario','Il ritmo del tempo','Dai spazio ai tuoi prossimi giorni.'],['percorso','Ascensione','Ogni esperienza costruisce la successiva.'],['contatti','Costellazioni umane','Le connessioni che danno forma al tuo mondo.'],['wishlist','Desideri in movimento','Le possibilità ancora da esplorare.'],['spese','Equilibrio','Una prospettiva sulle tue risorse.'],['esperimenti','Materia delle idee','Il luogo in cui la curiosità prende forma.']];
 const sculptures=[],moving=[];let selected=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,turn=0,tilt=0,zoom=8.5,transition=0,drag=null,lastMove=0;
 const earth=new THREE.Group();earth.add(globe,orbit);earth.traverse(o=>{if(o.isMesh)o.castShadow=true});group.add(earth);sculptures.push(earth);
 const white=new THREE.MeshStandardMaterial({color:'#e6e8dc',roughness:.55,metalness:.12});
 const pink=new THREE.MeshPhysicalMaterial({color:'#ee91bf',roughness:.2,metalness:.58,clearcoat:1});
 const glass=new THREE.MeshPhysicalMaterial({color:'#a2ddff',metalness:.22,roughness:.12,transparent:true,opacity:.72,clearcoat:1,side:THREE.DoubleSide});
 const add=(parent,geo,mat,x=0,y=0,z=0)=>{const o=new THREE.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
 const make=()=>{const g=new THREE.Group();group.add(g);sculptures.push(g);return g};
 const tempo=make();for(let i=0;i<11;i++){const r=.65+Math.sin(i/10*Math.PI)*.82;const o=add(tempo,new THREE.TorusGeometry(r,.085,12,80),i%3?chrome:accent,0,(i-5)*.28);o.rotation.x=Math.PI/2;moving.push({o,type:'time',i})}
 const ascent=make();for(let i=0;i<9;i++){const o=add(ascent,new THREE.BoxGeometry(1.6,.17,.7),i%3?white:chrome,0,(i-4)*.36);o.rotation.y=i*.42;moving.push({o,type:'ascent',i})}add(ascent,new THREE.OctahedronGeometry(.33),accent,0,1.9);
 const constellation=make();const locations=[];for(let i=0;i<10;i++){const a=i*2.399;const p=new THREE.Vector3(Math.cos(a)*(1+i%2*.4),Math.sin(i*1.6)*1.45,Math.sin(a)*1.1);locations.push(p);const o=add(constellation,new THREE.SphereGeometry(.19+i%3*.055,20,16),i%3?chrome:pink,...p.toArray());moving.push({o,type:'node',i,base:p.clone()})}for(let i=1;i<locations.length;i++){const curve=new THREE.LineCurve3(locations[i-1],locations[i]);add(constellation,new THREE.TubeGeometry(curve,1,.014,5,false),chrome)}
 const desire=make();const knot=add(desire,new THREE.TorusKnotGeometry(.95,.29,160,24,2,3),pink);moving.push({o:knot,type:'knot',i:0});const thin=add(desire,new THREE.TorusKnotGeometry(1.28,.018,160,6,2,3),chrome);thin.rotation.y=Math.PI;moving.push({o:thin,type:'wire',i:0});
 const balance=make();for(let i=0;i<5;i++){const o=add(balance,new THREE.TorusGeometry(1.3-i*.17,.1,14,90),i%2?glass:chrome,0,(i-2)*.28);o.rotation.set(i*.38,.2*i,0);moving.push({o,type:'balance',i})}add(balance,new THREE.IcosahedronGeometry(.4,1),accent);
 const idea=make();for(let i=0;i<9;i++){const curve=new THREE.CatmullRomCurve3(Array.from({length:50},(_,j)=>{const a=j/49*Math.PI*2;return new THREE.Vector3(Math.cos(a)*(1+.28*Math.cos(a*3)),Math.sin(a)*1.35,.4*Math.sin(a*2))}),true);const o=add(idea,new THREE.TubeGeometry(curve,75,.035,7,true),i%3?chrome:accent);o.rotation.y=i*Math.PI/9;moving.push({o,type:'bloom',i})}
 // A physical gallery: repeated portals, a circular plinth, shadows and floor inlays.
 const hall=new THREE.Group();scene.add(hall);const stone=new THREE.MeshStandardMaterial({color:'#d3ded9',roughness:.82});
 add(hall,new THREE.CylinderGeometry(2.28,2.35,.24,80),white,0,-2.03);
 add(hall,new THREE.CylinderGeometry(1.95,2.15,.18,80),stone,0,-2.23);
 const edge=add(hall,new THREE.TorusGeometry(2.26,.012,6,110),chrome,0,-1.90);edge.rotation.x=Math.PI/2;
 const floor=add(hall,new THREE.PlaneGeometry(60,60),new THREE.ShadowMaterial({opacity:.17}),0,-2.36);floor.rotation.x=-Math.PI/2;floor.castShadow=false;
 for(let i=0;i<4;i++){const z=-3-i*3,span=3.8+i*.6;add(hall,new THREE.BoxGeometry(.16,8,.25),stone,-span,1.2,z);add(hall,new THREE.BoxGeometry(.16,8,.25),stone,span,1.2,z);add(hall,new THREE.BoxGeometry(span*2,.16,.25),stone,0,5.2,z)}
 const spot=new THREE.SpotLight('#ffffff',65,25,.48,.65,1.3);spot.position.set(-3,6,4);spot.target.position.set(0,-1,0);spot.castShadow=true;spot.shadow.mapSize.set(1024,1024);spot.shadow.bias=-.0005;scene.add(spot,spot.target);
 const contour=new THREE.GridHelper(30,20,'#b2c3bf','#b2c3bf');contour.position.y=-2.34;contour.material.transparent=true;contour.material.opacity=.14;hall.add(contour);
 const panels=[];const artHosts=[document.querySelector('.auth-welcome'),document.getElementById('heroVisual'),...document.querySelectorAll('.page-hero')];
 artHosts.forEach(parent=>{if(!parent)return;parent.removeAttribute('aria-hidden');const ui=document.createElement('div');ui.className='museum-console';ui.innerHTML='<div class="museum-caption"><span class="museum-count"></span><strong></strong><small></small></div><div class="museum-buttons"><button type="button" data-art="prev" aria-label="Sala precedente">←</button><button type="button" data-art="next" aria-label="Sala successiva">→</button><button type="button" data-art="pause" aria-label="Ferma le animazioni">Ⅱ</button></div>';parent.append(ui);panels.push(ui);ui.querySelector('[data-art="prev"]').onclick=()=>go(-1);ui.querySelector('[data-art="next"]').onclick=()=>go(1);ui.querySelector('[data-art="pause"]').onclick=()=>{paused=!paused;refresh();renderStill()}});
 function refresh(){for(const ui of panels){ui.querySelector('.museum-count').textContent=`SALA ${String(selected+1).padStart(2,'0')} / 07 · MUSEO PERSONALE`;ui.querySelector('strong').textContent=rooms[selected][1];ui.querySelector('small').textContent=rooms[selected][2];const b=ui.querySelector('[data-art="pause"]');b.textContent=paused?'▷':'Ⅱ';b.setAttribute('aria-label',paused?'Riprendi le animazioni':'Ferma le animazioni');b.setAttribute('aria-pressed',String(paused))}}
 function choose(i){selected=(i+7)%7;sculptures.forEach((g,j)=>g.visible=j===selected);transition=paused||matchMedia('(prefers-reduced-motion: reduce)').matches?0:1;turn=0;tilt=0;refresh();renderStill()}
 function go(step){const next=(selected+step+7)%7;if(overlay.classList.contains('hidden')&&typeof window.showModule==='function')window.showModule(rooms[next][0]);else choose(next)}
 for(const holder of holders.values())attachDrag(holder);attachDrag(document.getElementById('authArt'));
 function attachDrag(el){el.classList.add('museum-interactive');el.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;turn+=(e.clientX-drag.x)*.008;tilt=THREE.MathUtils.clamp(tilt+(e.clientY-drag.y)*.005,-.5,.5);drag.x=e.clientX;drag.y=e.clientY;lastMove=performance.now();renderStill()});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,()=>{drag=null;el.classList.remove('dragging')})}
 choose(0);
 return {get paused(){return paused},selectModule(name){choose(Math.max(0,rooms.findIndex(r=>r[0]===name)))},selectMood(name){if(!overlay.classList.contains('hidden'))choose(name==='pink'?4:name==='night'?6:0)},tick(dt,time,compact){
  transition=Math.max(0,transition-dt*1.8);camera.position.z=zoom+Math.sin(transition*Math.PI)*1.5;camera.position.x=Math.sin(transition*Math.PI)*1.2;camera.position.y=.25;camera.lookAt(0,-.15,0);
  hall.visible=!compact;sculptures[selected].rotation.y=turn+(paused?0:Math.sin(time*.12)*.18);sculptures[selected].rotation.x=tilt;
  if(paused)return;
  for(const m of moving){if(!m.o.parent.visible)continue;const {o,i}=m;if(m.type==='time'){o.rotation.z=Math.sin(time*.6+i*.35)*.4;o.position.x=Math.sin(time*.5+i*.35)*.2}else if(m.type==='ascent')o.rotation.y=i*.42+Math.sin(time*.35+i*.2)*.25;else if(m.type==='knot'){o.rotation.x=time*.15;o.rotation.y=time*.2}else if(m.type==='wire')o.rotation.z=-time*.09;else if(m.type==='balance'){o.rotation.x=i*.38+time*.12;o.rotation.y=i*.2+time*.16}else if(m.type==='bloom'){o.rotation.y=i*Math.PI/9+Math.sin(time*.3)*.28;o.scale.setScalar(1+Math.sin(time*.6+i*.25)*.08)}}
 },dispose(){}};
}
