/* One UI for the authenticated module and the standalone sandbox page. */
(()=>{
 const $=id=>document.getElementById(id);if(!$('mod-paypal'))return;const standalone=document.body.dataset.paypalStandalone==='true';
 const owner=()=>standalone?'standalone':typeof currentUser!=='undefined'?currentUser?.id||null:null;
 let activeOwner=null,config=null,sdkPromise=null,buttons=null,pending=null,attemptId=null,busy=false,initialized=false,renderVersion=0,finished=false;
 let cart=[];
 function saveCart(){try{localStorage.setItem(key('cart'),JSON.stringify(cart))}catch{}}
 function renderShop(){
  if(!config)return;const catalog=$('shopCatalog'),basket=$('shopCart');catalog.replaceChildren();basket.replaceChildren();
  const frozen=busy||!!pending||!!buttons;
  for(const [i,p] of config.products.entries()){
   const card=document.createElement('article');card.className='shop-product';
   const visual=document.createElement('div');visual.className='shop-art shop-art-'+i;visual.setAttribute('aria-hidden','true');visual.textContent=i===0?'STUDIO / 01':'CLUB / 02';
   const title=document.createElement('h2');title.textContent=p.name;const price=document.createElement('p');price.textContent=Number(p.value).toLocaleString('it-IT',{style:'currency',currency:'EUR'});
   const add=document.createElement('button');add.textContent='Aggiungi al carrello +';add.disabled=frozen;add.onclick=()=>{const row=cart.find(x=>x.id===p.id);if(row&&row.quantity>=10){$('shopMessage').textContent='Massimo 10 pezzi per articolo.';return}if(row)row.quantity++;else cart.push({id:p.id,quantity:1});saveCart();renderShop();$('shopMessage').textContent=p.name+' aggiunto al carrello.'};card.append(visual,title,price,add);catalog.append(card);
  }
  let cents=0;
  for(const row of cart){const p=config.products.find(x=>x.id===row.id);if(!p)continue;cents+=Math.round(Number(p.value)*100)*row.quantity;const line=document.createElement('div');line.className='shop-line';const label=document.createElement('span');label.textContent=p.name+' · '+(Number(p.value)*row.quantity).toLocaleString('it-IT',{style:'currency',currency:'EUR'});const qty=document.createElement('input');qty.type='number';qty.min='1';qty.max='10';qty.value=row.quantity;qty.setAttribute('aria-label','Quantità '+p.name);qty.disabled=frozen;qty.onchange=()=>{const n=Number(qty.value);if(!Number.isInteger(n)||n<1||n>10){qty.value=row.quantity;return}row.quantity=n;attemptId=null;saveCart();renderShop()};const remove=document.createElement('button');remove.textContent='Rimuovi';remove.disabled=frozen;remove.setAttribute('aria-label','Rimuovi '+p.name);remove.onclick=()=>{cart=cart.filter(x=>x.id!==row.id);attemptId=null;saveCart();renderShop()};line.append(label,qty,remove);basket.append(line)}
  if(!cart.length)basket.textContent='Il carrello è vuoto. Scegli un articolo qui sopra.';
  $('paypalTotal').textContent=(cents/100).toLocaleString('it-IT',{style:'currency',currency:'EUR'});$('paypalStart').disabled=!config.configured||!cart.length||frozen;
 }
 const key=kind=>'dv-paypal-sandbox:'+activeOwner+':'+kind;
 function read(kind,fallback){try{return JSON.parse((kind==='pending'?sessionStorage:localStorage).getItem(key(kind))||'null')||fallback}catch{return fallback}}
 function storePending(){try{if(pending)sessionStorage.setItem(key('pending'),JSON.stringify(pending));else sessionStorage.removeItem(key('pending'))}catch{}}
 function history(){const rows=read('history',[]);return Array.isArray(rows)?rows.slice(0,30).filter(x=>x&&typeof x.orderId==='string'&&typeof x.status==='string'):[]}
 function record(data){const entry={environment:'sandbox',orderId:data.orderId,status:data.status,captureId:data.captureId||null,amount:data.amount,currency:data.currency,checkedAt:data.checkedAt||new Date().toISOString()};const rows=history().filter(x=>x.orderId!==entry.orderId);rows.unshift(entry);try{localStorage.setItem(key('history'),JSON.stringify(rows.slice(0,30)))}catch{event('Il browser non ha conservato il registro locale.')}renderHistory()}
 function event(text){const li=document.createElement('li');const time=document.createElement('time');time.textContent=new Date().toLocaleTimeString('it-IT');const label=document.createElement('span');label.textContent=text;li.append(time,label);$('paypalEvents').prepend(li);while($('paypalEvents').children.length>12)$('paypalEvents').lastChild.remove()}
 function outcome(text,error=false){$('paypalOutcome').textContent=text;$('paypalOutcome').classList.toggle('payment-error',error)}
 function phase(value){const order=['ready','created','approved','completed'],i=order.indexOf(value);document.querySelectorAll('[data-pay-step]').forEach(el=>el.classList.toggle('done',order.indexOf(el.dataset.payStep)<=i))}
 function lock(value){busy=value;$('paypalProduct').disabled=value||!!pending;$('paypalNew').disabled=value;$('paypalVerify').disabled=value||!pending;$('paypalRetryCapture').disabled=value;renderShop();}
 async function call(action,extra={}){const account=activeOwner;const response=await fetch('/api/paypal-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra}),signal:AbortSignal.timeout(50000)});const data=await response.json();if(account!==owner()||account!==activeOwner)throw Error('L’account è cambiato.');if(!response.ok){const error=Error(data.error||'Richiesta non riuscita.');error.code=data.code;throw error}if(data.environment!=='sandbox')throw Error('Ambiente di pagamento inatteso.');return data}
 async function verify(capture=false){if(!pending||busy)return;lock(true);try{const data=await call(capture?'capture':'status',{orderId:pending.orderId,ticket:pending.ticket});record(data);if(data.completed){finished=true;cart=[];saveCart();phase('completed');outcome('Pagamento di prova completato e verificato. Nessun denaro reale è stato trasferito.');event('Conferma verificata · '+data.orderId);$('paypalRetryCapture').hidden=true;await Promise.resolve(buttons?.close()).catch(()=>{});buttons=null;$('paypalButtons').replaceChildren()}else{event('Stato PayPal: '+data.status);outcome(data.status==='APPROVED'?'Ordine approvato: puoi riprovare la conferma.':'Ordine verificato: '+data.status+'. Non risulta completato.');$('paypalRetryCapture').hidden=data.status!=='APPROVED';phase(data.status==='APPROVED'?'approved':'created')}}catch(error){event(error.code||'Verifica non riuscita');outcome(error.message||'Verifica non riuscita. Riprova.',true);$('paypalVerify').disabled=false}finally{lock(false)}}
 function loadSdk(){if(window.dvPayPal)return Promise.resolve(window.dvPayPal);if(sdkPromise)return sdkPromise;sdkPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');const url=new URL('https://www.paypal.com/sdk/js');url.search=new URLSearchParams({'client-id':config.clientId,currency:'EUR',intent:'capture',components:'buttons','buyer-country':'IT','disable-funding':'card,credit,paylater,venmo'});script.src=url;script.dataset.namespace='dvPayPal';script.async=true;const timer=setTimeout(()=>{script.remove();sdkPromise=null;reject(Error('Il checkout impiega troppo tempo a caricarsi. Controlla la connessione e riprova.'))},20000);script.onload=()=>{clearTimeout(timer);if(window.dvPayPal)resolve(window.dvPayPal);else{sdkPromise=null;reject(Error('Checkout non disponibile.'))}};script.onerror=()=>{clearTimeout(timer);script.remove();sdkPromise=null;reject(Error('Impossibile caricare PayPal. Controlla connessione e blocchi del browser.'))};document.head.append(script)});return sdkPromise}
 async function start(){if(busy||!config?.configured||!activeOwner||!cart.length)return;const version=++renderVersion,account=activeOwner;lock(true);$('paypalStart').disabled=true;try{const paypal=await loadSdk();if(version!==renderVersion||account!==owner())return;await Promise.resolve(buttons?.close()).catch(()=>{});$('paypalButtons').replaceChildren();buttons=paypal.Buttons({fundingSource:paypal.FUNDING.PAYPAL,style:{layout:'vertical',color:'gold',shape:'rect',label:'pay'},createOrder:async()=>{if(account!==activeOwner||account!==owner())throw Error('Accedi di nuovo.');if(finished)throw Error('Avvia un nuovo test.');lock(true);outcome('Creazione ordine Sandbox…');const product=$('paypalProduct').value;attemptId=attemptId||crypto.randomUUID();try{const data=await call('create',{items:cart.map(x=>({...x})),attemptId});pending={orderId:data.orderId,ticket:data.ticket,product,amount:data.amount,currency:data.currency,items:cart.map(x=>({...x}))};storePending();phase('created');event('Ordine creato · '+data.orderId);return data.orderId}catch(error){outcome(error.message,true);lock(false);throw error}},onApprove:async data=>{if(account!==activeOwner||account!==owner()||data.orderID!==pending?.orderId){outcome('Ordine non corrispondente alla sessione.',true);lock(false);return}phase('approved');event('Approvazione ricevuta. Conferma sul server…');lock(false);await verify(true)},onCancel:()=>{if(account!==activeOwner)return;lock(false);outcome('Checkout annullato. Nessun pagamento è stato confermato.');event('Checkout annullato dal visitatore.')},onError:()=>{if(account!==activeOwner)return;lock(false);outcome('Checkout non concluso. Se un ordine è già stato creato, verificane lo stato prima di riprovare.',true);event('Errore nel checkout: esito da verificare.')}});await buttons.render('#paypalButtons');phase('ready');event('Pulsante PayPal Sandbox pronto.');outcome('Apri PayPal e accedi con il conto acquirente Sandbox.');$('paypalStart').hidden=true}catch(error){outcome(error.message,true);$('paypalStart').disabled=false}finally{if(account===activeOwner){lock(false);if(!buttons)$('paypalStart').disabled=false}}}
 function renderHistory(){$('paypalHistory').replaceChildren();const rows=history();if(!rows.length){$('paypalHistory').textContent='Il primo test comparirà qui dopo una verifica dell’ordine.';return}for(const x of rows){const row=document.createElement('article');const title=document.createElement('strong');title.textContent=x.status;const id=document.createElement('span');id.textContent=x.orderId;const info=document.createElement('small');info.textContent=(x.amount||'—')+' '+(x.currency||'EUR')+' · '+new Date(x.checkedAt).toLocaleString('it-IT');row.append(title,id,info);$('paypalHistory').append(row)}}
 function newTest(){if(busy)return;renderVersion++;Promise.resolve(buttons?.close()).catch(()=>{});buttons=null;pending=null;storePending();attemptId=null;finished=false;$('paypalButtons').replaceChildren();$('paypalStart').hidden=false;$('paypalStart').disabled=!config?.configured;$('paypalRetryCapture').hidden=true;lock(false);phase('');renderShop();outcome('Carrello sbloccato: modifica gli articoli e avvia il checkout.');event('Nuova sessione di prova.');}
 async function initialize(){const id=owner();if(!id)return;if(initialized&&id===activeOwner)return;activeOwner=id;cart=read('cart',[]);if(!Array.isArray(cart))cart=[];cart=cart.filter(x=>x&&typeof x.id==='string'&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=10);pending=read('pending',null);if(!pending||typeof pending.ticket!=='string')pending=null;attemptId=null;finished=false;$('paypalEvents').replaceChildren();renderHistory();try{const response=await fetch('/api/paypal-config',{cache:'no-store',signal:AbortSignal.timeout(12000)});const data=await response.json();if(id!==owner())return;if(!response.ok||data.environment!=='sandbox')throw Error('Configurazione non disponibile.');config=data;cart=cart.filter(x=>config.products.some(p=>p.id===x.id));if(Array.isArray(pending?.items))cart=pending.items;renderShop();$('paypalProduct').replaceChildren();for(const product of data.products){const o=new Option(product.name+' · '+product.value+' '+product.currency,product.id);$('paypalProduct').append(o)}if(pending)$('paypalProduct').value=pending.product;price();$('paypalConfigStatus').textContent=data.configured?'Credenziali Sandbox presenti. Il test ne verificherà il funzionamento.':'Da configurare: aggiungi Client ID e Secret Sandbox su Cloudflare e pubblica di nuovo il sito.';$('paypalStart').disabled=!data.configured||!!pending;initialized=true;lock(false);event(data.configured?'Ambiente Sandbox configurato.':'In attesa delle credenziali Sandbox.');if(pending){phase('created');outcome('È presente un ordine precedente: verificane lo stato prima di avviare un altro test.')}}catch(error){$('paypalConfigStatus').textContent=error.message||'Impossibile leggere la configurazione.';initialized=false}}
 function price(){renderShop()}
 $('paypalStart').onclick=start;$('paypalVerify').onclick=()=>verify(false);$('paypalRetryCapture').onclick=()=>verify(true);$('paypalNew').onclick=()=>{newTest();if(!initialized)initialize()};$('paypalProduct').onchange=()=>{attemptId=null;price()};$('paypalExport').onclick=()=>{const blob=new Blob([JSON.stringify({environment:'sandbox',notAnInvoice:true,exportedAt:new Date().toISOString(),tests:history()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='paypal-sandbox-registro.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)};
 function leaveAccount(){if(activeOwner===owner())return;renderVersion++;Promise.resolve(buttons?.close()).catch(()=>{});buttons=null;initialized=false;config=null;pending=null;activeOwner=null;cart=[];busy=false;$('shopCart').replaceChildren();$('shopCatalog').replaceChildren();$('shopMessage').textContent='';$('paypalTotal').textContent='—';$('paypalButtons').replaceChildren();$('paypalEvents').replaceChildren();$('paypalHistory').replaceChildren();$('paypalStart').hidden=false;$('paypalStart').disabled=true;outcome('');}
 if(standalone)initialize();else{addEventListener('workspace:module',e=>{if(e.detail==='paypal')initialize()});addEventListener('personal:appearance',leaveAccount);new MutationObserver(leaveAccount).observe($('authOverlay'),{attributes:true,attributeFilter:['class']})}
})();
