/* User-owned preferences. Never use user metadata for authorization. */
let preferenceUserId=null;
const PERSONAL_DEFAULTS={theme:'light',accent:'burgundy',motion:'active',start:'home',quality:'auto',avatar:'monogram',bio:'',sections:'all'};
const PERSONAL_ACCENTS={burgundy:'#922c32',forest:'#2c644e',midnight:'#354d82',copper:'#955025'};
function normalizedPreferences(value={}){
 if(!value||typeof value!=='object')value={};
 return {quality:['auto','lite','full'].includes(value.quality)?value.quality:'auto',avatar:['monogram','rose','onyx'].includes(value.avatar)?value.avatar:'monogram',bio:typeof value.bio==='string'?value.bio.slice(0,160):'',sections:['all','essentials'].includes(value.sections)?value.sections:'all',theme:['light','dark'].includes(value.theme)?value.theme:'light',accent:Object.hasOwn(PERSONAL_ACCENTS,value.accent)?value.accent:'burgundy',motion:value.motion==='paused'?'paused':'active',start:['home','calendario','percorso','wishlist','spese','esperimenti','outfit','calcio'].includes(value.start)?value.start:'home'};
}
function personalStorageKey(key){return preferenceUserId?`dv-user:${preferenceUserId}:${key}`:`dv-guest:${key}`;}
function readPersonalPreference(key,fallback=null){try{return localStorage.getItem(personalStorageKey(key))??fallback}catch{return fallback}}
function writePersonalPreference(key,value){try{localStorage.setItem(personalStorageKey(key),String(value))}catch{}}
function applyPersonalAppearance(p){
 document.documentElement.setAttribute('data-theme',p.theme);
 const dark=p.theme==='dark',color=PERSONAL_ACCENTS[p.accent];
 document.documentElement.style.setProperty('--accent',color);
 document.documentElement.style.setProperty('--accent-soft',dark?({burgundy:'#f0a4a3',forest:'#9bd0b4',midnight:'#adbee8',copper:'#edbd96'}[p.accent]):color);
 document.documentElement.style.setProperty('--accent-strong',color);
 document.documentElement.style.setProperty('--accent-dim',color+'12');document.documentElement.style.setProperty('--accent-line',color+'66');
 window.dispatchEvent(new CustomEvent('personal:appearance',{detail:p}));
}
function initializePersonalPreferences(user){
 preferenceUserId=user.id;
 const cloud=normalizedPreferences(user.user_metadata?.workspace_preferences);
 const p=normalizedPreferences({...cloud,theme:readPersonalPreference('theme',cloud.theme),accent:readPersonalPreference('accent',cloud.accent),motion:readPersonalPreference('motion',cloud.motion)});
 for(const [key,value] of Object.entries(p))writePersonalPreference(key,value);
 applyPersonalAppearance(p);return p;
}
function resetPersonalPreferences(){preferenceUserId=null;applyPersonalAppearance(PERSONAL_DEFAULTS);}
function mountPersonalSettings(){
 const dialog=document.createElement('dialog');dialog.id='personalSettings';dialog.className='personal-settings';dialog.setAttribute('aria-labelledby','personalSettingsTitle');
 dialog.innerHTML='<form id="personalSettingsForm"><div class="personal-settings-head"><span class="eyebrow">LA TUA EDIZIONE PERSONALE</span><button type="button" id="closePersonalSettings" aria-label="Chiudi personalizzazione">×</button></div><h2 id="personalSettingsTitle">Fallo tuo.</h2><p>Contenuti e preferenze appartengono al tuo account.</p><label for="personalName">Come vuoi essere chiamato?</label><input id="personalName" maxlength="70" autocomplete="nickname" required><label for="personalBio">La tua firma</label><input id="personalBio" maxlength="160" placeholder="Una frase che ti rappresenta"><label for="personalAvatar">Pass personale</label><select id="personalAvatar"><option value="monogram">Avorio · monogramma</option><option value="rose">Rosé · monogramma</option><option value="onyx">Onice · monogramma</option></select><label for="personalQuality">Esperienza</label><select id="personalQuality"><option value="auto">Automatica · leggera su mobile</option><option value="lite">Leggera · senza 3D</option><option value="full">Completa · passerella 3D</option></select><label for="personalSections">La tua home</label><select id="personalSections"><option value="all">Completa · editoriale e strumenti</option><option value="essentials">Essenziale · solo i miei strumenti</option></select><label for="personalTheme">Tema</label><select id="personalTheme"><option value="light">Avorio</option><option value="dark">Notturno</option></select><label for="personalAccent">Colore</label><select id="personalAccent"><option value="burgundy">Bordeaux</option><option value="forest">Verde bosco</option><option value="midnight">Blu notte</option><option value="copper">Rame</option></select><label for="personalMotion">Animazioni</label><select id="personalMotion"><option value="active">Attive</option><option value="paused">In pausa</option></select><label for="personalStart">All’accesso apri</label><select id="personalStart"><option value="home">La mia edizione</option><option value="calendario">Il mio calendario</option><option value="percorso">Il mio percorso</option><option value="wishlist">La mia wishlist</option><option value="spese">Le mie spese</option><option value="esperimenti">Il laboratorio</option><option value="outfit">Outfit 3D</option><option value="calcio">Bologna &amp; Napoli</option></select><button class="primary-button" id="savePersonalSettings" type="submit">Salva nel mio account ↗</button><p id="personalSettingsMessage" role="status" aria-live="polite"></p></form>';
 document.body.append(dialog);
 const trigger=document.createElement('button');trigger.type='button';trigger.className='sidebar-focus';trigger.textContent='✦ Personalizza il tuo spazio';document.querySelector('.sidebar-bottom').prepend(trigger);
 const mobileTrigger=document.createElement('button');mobileTrigger.type='button';mobileTrigger.className='cinema-close';mobileTrigger.textContent='Personalizza';document.querySelector('.cinema-utilities')?.prepend(mobileTrigger);
 const get=id=>document.getElementById(id);
 function open(){if(!currentUser||!document.getElementById('authOverlay').classList.contains('hidden'))return;document.getElementById('cinemaMenu')?.close();const p=normalizedPreferences({...currentUser.user_metadata?.workspace_preferences,theme:document.documentElement.getAttribute('data-theme'),accent:readPersonalPreference('accent',currentUser.user_metadata?.workspace_preferences?.accent||'burgundy'),motion:document.body.classList.contains('motion-paused')?'paused':'active'});get('personalName').value=currentUser.user_metadata?.full_name||currentUser.user_metadata?.name||currentUser.email?.split('@')[0]||'';for(const k of ['Theme','Accent','Motion','Start','Quality','Avatar','Bio','Sections'])get('personal'+k).value=p[k.toLowerCase()];get('personalSettingsMessage').textContent='';dialog.showModal();}
 trigger.onclick=open;mobileTrigger.onclick=open;get('closePersonalSettings').onclick=()=>dialog.close();
 get('personalSettingsForm').onsubmit=async e=>{e.preventDefault();const button=get('savePersonalSettings'),message=get('personalSettingsMessage');const owner=preferenceUserId;const name=get('personalName').value.trim();if(!name){message.textContent='Inserisci un nome.';return}const p=normalizedPreferences({theme:get('personalTheme').value,accent:get('personalAccent').value,motion:get('personalMotion').value,start:get('personalStart').value,quality:get('personalQuality').value,avatar:get('personalAvatar').value,bio:get('personalBio').value.trim(),sections:get('personalSections').value});button.disabled=true;message.textContent='Salvataggio…';try{const user=await getCurrentUser();if(!owner||user?.id!==owner)throw Error('Accedi di nuovo per salvare.');const response=await authorizedFetch(`${AUTH_ENDPOINT}/user`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:{full_name:name,workspace_preferences:p}})});const updated=await response.json();if(!response.ok)throw Error(updated.msg||updated.message||'Salvataggio non riuscito.');if(preferenceUserId!==owner||!accessToken)return;currentUser=updated;for(const [key,value] of Object.entries(p))writePersonalPreference(key,value);applyPersonalAppearance(p);applyDisplayName(updated);get('sidebarName').textContent=name;get('profileInitials').textContent=name.split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase();message.textContent='Salvato. Le preferenze sono collegate al tuo account.';}catch(error){message.textContent=error.message||'Salvataggio non riuscito.'}finally{button.disabled=false}};
 new MutationObserver(()=>{if(!get('authOverlay').classList.contains('hidden'))dialog.close()}).observe(get('authOverlay'),{attributes:true,attributeFilter:['class']});
}
