(()=>{
 const chapters=[['SUPPORTO','Prima le persone.\nPoi la soluzione.','Ascoltare, capire il problema e rendere la tecnologia più semplice da usare.','SUPPORTO IT',"Let's solve it.",['Ascolta','Analizza','Risolvi']],['AUTOMAZIONE','Meno ripetizioni.\nPiù tempo utile.','Script e processi chiari per semplificare le attività quotidiane.','POWERSHELL','Make it simpler.',['Pianifica','Automatizza','Verifica']],['PROGETTI','Un’idea prende forma.\nE diventa uno strumento.','Interfacce web, inventario e integrazioni: la soluzione parte da un bisogno concreto.','WEB & INTEGRAZIONI','Build with purpose.',['Progetta','Costruisci','Migliora']],['CURIOSITÀ','Il prossimo progetto\ninizia da una domanda.','Tecnologia, calcio, gaming e moda. Punti di vista diversi, la stessa voglia di imparare.','PERSONAL SPACE','Stay curious.',['Esplora','Impara','Condividi']]];
 const $=id=>document.getElementById(id),story=$('racconto'),device=$('storyDevice'),motion=$('storyMotion'),query=matchMedia('(prefers-reduced-motion:reduce)'),short=matchMedia('(max-height:620px)');let paused=false,frame=0,index=-1;
 function display(i){if(i===index)return;index=i;document.querySelectorAll('[data-chapter]').forEach((b,j)=>{if(j===i)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});const c=chapters[i];$('storyLabel').textContent=String(i+1).padStart(2,'0')+' / '+c[0];$('storyTitle').textContent=c[1];$('storyTitle').style.whiteSpace='pre-line';$('storyText').textContent=c[2];$('screenLabel').textContent=c[3];$('screenTitle').textContent=c[4];document.querySelectorAll('.screen-grid>div').forEach((el,j)=>{el.replaceChildren();const small=document.createElement('small');small.textContent='0'+(j+1);el.append(small,c[5][j])});$('storyCount').textContent=String(i+1).padStart(2,'0')+' — 04'}
 function paint(){frame=0;if(document.body.classList.contains('static-story'))return;const r=story.getBoundingClientRect(),travel=Math.max(1,story.offsetHeight-document.querySelector('.story-stage').offsetHeight),p=Math.max(0,Math.min(1,(parseFloat(getComputedStyle(document.querySelector('.story-stage')).top)-r.top)/travel)),i=Math.min(3,Math.floor(p*4));display(i);const rot=-26+Math.sin(p*Math.PI*2)*24,tilt=8-Math.sin(p*Math.PI)*16,zoom=1+Math.sin(p*Math.PI)*.12;device.style.transform=`rotateX(${tilt}deg) rotateY(${rot}deg) scale(${zoom})`;device.style.setProperty('--phase',p);device.querySelector('.note-one').style.transform=`translateZ(${70+Math.sin(p*Math.PI)*75}px) translateY(${-p*28}px)`;device.querySelector('.note-two').style.transform=`translateZ(${95+p*40}px) translateX(${Math.sin(p*Math.PI)*25}px)`;$('storyProgress').style.transform=`scaleX(${p})`}
 function schedule(){if(!frame)frame=requestAnimationFrame(paint)}
 function mode(){const still=paused||query.matches||short.matches;document.body.classList.toggle('static-story',still);motion.textContent=paused?'Attiva movimento':'Pausa movimento';motion.disabled=query.matches||short.matches;motion.setAttribute('aria-pressed',String(still));document.querySelector('.static-chapters')?.remove();if(still){display(0);const wrap=document.createElement('div');wrap.className='static-chapters';chapters.slice(1).forEach(c=>{const a=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=c[1];p.textContent=c[2];a.append(h,p);wrap.append(a)});story.append(wrap)}else schedule()}
 motion.onclick=()=>{paused=!paused;mode()};query.addEventListener('change',mode);short.addEventListener('change',mode);addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);mode();schedule();
 const config=window.DV_PUBLIC_CONTACT||{},host=$('publicContacts'),links=[];for(const [name,value] of [['Email',config.email],['Instagram',config.instagram],['Sito',config.website]]){if(!value)continue;let href;if(name==='Email'){if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(value))continue;href='mailto:'+value}else{try{const u=new URL(value);if(u.protocol!=='https:')continue;href=u.href}catch{continue}}const a=document.createElement('a');a.href=href;a.textContent=name+' ↗';a.rel='noopener noreferrer';if(name!=='Email')a.target='_blank';links.push(a)}if(links.length)host.replaceChildren(...links);
 if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
})();
