/* A single shared WebGL scene. Touch scrolling remains entirely native. */
(()=>{
 const auth=document.getElementById('authOverlay'),home=document.getElementById('mod-home'),cover=document.querySelector('.auth-welcome'),intro=document.querySelector('.runway-premiere');
 const coverHost=document.createElement('div');coverHost.className='runway-canvas-host cover-runway';coverHost.setAttribute('aria-hidden','true');cover.prepend(coverHost);
 const tour=document.createElement('section');tour.className='runway-tour';tour.setAttribute('aria-label','La tua passerella personale');
 const chapters=[['calendario','01 / THE OPENING','Il tempo,<br><em>su misura.</em>','Ogni appuntamento ha il suo momento.','Apri il calendario'],['percorso','02 / THE SIGNATURE','Lascia<br><em>il segno.</em>','Il percorso che racconta chi sei.','Esplora il percorso'],['contatti','03 / THE FRONT ROW','Le persone.<br><em>In prima fila.</em>','I contatti che fanno parte del tuo mondo.','Apri i contatti'],['wishlist','04 / THE DESIRE','Il prossimo<br><em>desiderio.</em>','Pezzi da collezionare. Idee da realizzare.','Sfoglia la wishlist'],['spese','05 / THE BALANCE','Ogni scelta,<br><em>il suo valore.</em>','Le tue spese, con una prospettiva chiara.','Apri le spese'],['esperimenti','06 / THE AFTERPARTY','Oltre<br><em>la passerella.</em>','Giochi, curiosità e nuovi mondi da esplorare.','Entra nel laboratorio']];
 tour.innerHTML='<div class="runway-sticky"><div class="runway-canvas-host tour-runway" aria-hidden="true"></div><div class="runway-tour-shade" aria-hidden="true"></div><div class="runway-label"><span>DV / THE RUNWAY</span><span>COLLECTION 2026</span></div><div class="runway-top-actions"><button type="button" class="runway-sound" aria-pressed="false">Audio off</button><button type="button" class="runway-pause" aria-pressed="false">Pausa scena</button><a href="#runwayWorkspace">Vai ai tuoi strumenti ↓</a></div><div class="runway-cover-title"><span>YOUR LIFE. YOUR COLLECTION.</span><h2>Life is a<br><em>runway.</em></h2><p>Scorri. Entra in scena.</p></div><div class="runway-chapter-cards"></div><nav class="runway-steps" aria-label="Uscite della sfilata"></nav><div class="runway-tour-footer"><span class="runway-status">PRELUDE / TAKE YOUR SEAT</span><span>SCROLL TO EXPLORE ↓</span></div></div>';
 const sticky=tour.querySelector('.runway-sticky'),tourHost=tour.querySelector('.tour-runway'),cards=tour.querySelector('.runway-chapter-cards'),stepNav=tour.querySelector('.runway-steps');
 chapters.forEach(([id,kicker,title,copy,label],i)=>{const card=document.createElement('article');card.className='runway-chapter';card.inert=true;card.setAttribute('aria-hidden','true');card.innerHTML='<span>'+kicker+'</span><h2>'+title+'</h2><p>'+copy+'</p><button type="button">'+label+' ↗</button>';card.querySelector('button').onclick=()=>showModule(id,{transition:true});cards.append(card);const step=document.createElement('button');step.type='button';step.textContent=String(i+1).padStart(2,'0');step.setAttribute('aria-label',label);step.onclick=()=>{const travel=Math.max(1,tour.offsetHeight-sticky.offsetHeight);const y=tour.getBoundingClientRect().top+scrollY+travel*((i+1.35)/7);window.scrollTo({top:y,behavior:paused()?'instant':'smooth'});};stepNav.append(step)});
 const anchor=document.createElement('div');anchor.id='runwayWorkspace';anchor.tabIndex=-1;home.prepend(anchor);home.prepend(tour);
 tour.querySelector('a').onclick=e=>{e.preventDefault();anchor.scrollIntoView({behavior:paused()?'instant':'smooth',block:'start'});anchor.focus({preventScroll:true})};
 const reduced=matchMedia('(prefers-reduced-motion:reduce)'),paused=()=>reduced.matches||document.body.classList.contains('motion-paused');
 let api=null,currentHost=null,pending=0,activeChapter=-2,introStart=performance.now(),introOpen=intro?.open||false;
 const stepButtons=[...stepNav.children],chapterCards=[...cards.children],pauseButton=tour.querySelector('.runway-pause');
 pauseButton.onclick=()=>document.getElementById('motionToggle').click();
 function progress(){const r=tour.getBoundingClientRect();return Math.max(0,Math.min(1,-r.top/Math.max(1,r.height-sticky.offsetHeight)))}
 function paint(){pending=0;const inIntro=!!intro?.open,atAuth=!auth.classList.contains('hidden');let host=inIntro?document.getElementById('introRunwayHost'):atAuth?coverHost:tourHost;
  if(inIntro&&!introOpen)introStart=performance.now();introOpen=inIntro;
  const p=progress(),index=Math.min(5,Math.floor(p*7)-1);
  if(index!==activeChapter){activeChapter=index;tour.classList.toggle('runway-start',index<0);chapterCards.forEach((c,i)=>{const on=i===index;c.classList.toggle('is-active',on);c.inert=!on;c.setAttribute('aria-hidden',String(!on))});stepButtons.forEach((b,i)=>{if(i===index)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});tour.querySelector('.runway-status').textContent=index<0?'PRELUDE / TAKE YOUR SEAT':chapters[index][1]}
  pauseButton.textContent=paused()?'Riprendi scena':'Pausa scena';pauseButton.setAttribute('aria-pressed',String(paused()));
  if(api){if(inIntro){const video=intro.querySelector('video');if(video&&!video.paused)video.pause();}if(currentHost!==host){api.attach(host);currentHost=host;}api.setState(inIntro?'intro':atAuth?'cover':'tour',inIntro?Math.min(1,(performance.now()-introStart)/10500):p,inIntro||atAuth||home.classList.contains('active'))}
  if(inIntro&&!paused())pending=requestAnimationFrame(paint);
 }
 function request(){if(!pending)pending=requestAnimationFrame(paint)}
 const authObserver=new MutationObserver(()=>{request();if(!auth.classList.contains('hidden'))mute()});authObserver.observe(auth,{attributes:true,attributeFilter:['class']});const introObserver=new MutationObserver(request);if(intro)introObserver.observe(intro,{attributes:true,attributeFilter:['open']});
 addEventListener('scroll',request,{passive:true});addEventListener('resize',request);addEventListener('workspace:module',request);addEventListener('space:motion',request);reduced.addEventListener('change',request);
 import('./runway-scene.js').then(({mountRunway})=>{api=mountRunway(intro?.open?document.getElementById('introRunwayHost'):coverHost);if(api){document.body.classList.add('live-runway');request()}else document.body.classList.add('runway-fallback')}).catch(()=>document.body.classList.add('runway-fallback'));paint();
 // Low-volume original electronic atmosphere, strictly opt-in, generated locally.
 let audio=null,master=null,sounding=false;const soundButton=tour.querySelector('.runway-sound');
 soundButton.onclick=async()=>{try{if(!audio){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error();audio=new Audio();master=audio.createGain();master.gain.value=0;master.connect(audio.destination);for(const freq of [55,82.41,110.1]){const osc=audio.createOscillator(),g=audio.createGain();osc.type='sine';osc.frequency.value=freq;g.gain.value=.07;osc.connect(g);g.connect(master);osc.start();}const lfo=audio.createOscillator(),depth=audio.createGain();lfo.frequency.value=1.65;depth.gain.value=.018;lfo.connect(depth);depth.connect(master.gain);lfo.start();}sounding=!sounding;if(sounding){await audio.resume();master.gain.setTargetAtTime(.12,audio.currentTime,.3)}else{master.gain.setTargetAtTime(0,audio.currentTime,.1);await audio.suspend()}soundButton.textContent=sounding?'Audio on':'Audio off';soundButton.setAttribute('aria-pressed',String(sounding))}catch{soundButton.textContent='Audio non disponibile';soundButton.disabled=true}};
 function mute(){if(audio){audio.suspend().catch(()=>{});sounding=false;soundButton.textContent='Audio off';soundButton.setAttribute('aria-pressed','false')}}
 document.addEventListener('visibilitychange',()=>{if(document.hidden)mute()});addEventListener('workspace:module',()=>{if(!home.classList.contains('active'))mute()});
 addEventListener('pagehide',e=>{cancelAnimationFrame(pending);pending=0;mute();if(!e.persisted){authObserver.disconnect();introObserver.disconnect();api?.dispose();audio?.close()}});addEventListener('pageshow',request);
})();
