/* Only named workspace forms, never authentication fields. Drafts remain on this device. */
function workspaceDraftKey(formId){return currentUser?.id?`dv-draft:${currentUser.id}:${formId}`:null}
function clearWorkspaceDraft(formId){const key=workspaceDraftKey(formId);if(key)try{localStorage.removeItem(key)}catch{}window.dispatchEvent(new CustomEvent('workspace:draft-cleared',{detail:formId}))}
(()=>{
 const specs={wlForm:{module:'wishlist',editing:()=>editingWlId,find:id=>wishlistEntries.find(x=>x.id===id),edit:editWishlistItem,reset:resetWishlistForm},spForm:{module:'spese',editing:()=>editingSpeseId,find:id=>expenseEntries.find(x=>x.id===id),edit:editExpense,reset:resetSpeseForm},evForm:{module:'calendario',editing:()=>editingEventId,find:id=>Object.values(events).flat().find(x=>x.id===id),edit:editEvent,reset:resetEventForm}};
 for(const [id,spec] of Object.entries(specs)){const form=document.getElementById(id);const fields=[...form.querySelectorAll('input[id],textarea[id],select[id]')].filter(x=>!['password','file','hidden'].includes(x.type));const banner=document.createElement('div');banner.className='workspace-draft';banner.innerHTML='<span role="status"></span><button type="button">Riprendi bozza</button><button type="button">Elimina bozza</button>';form.before(banner);const [restore,discard]=banner.querySelectorAll('button');
 function read(){const key=workspaceDraftKey(id);if(!key)return null;try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(!raw||raw.version!==1||typeof raw.values!=='object'||!Number.isFinite(raw.at))return null;return raw}catch{return null}}
 function offer(){const draft=read();banner.hidden=!draft;if(draft){banner.querySelector('span').textContent='Bozza su questo dispositivo · '+new Date(draft.at).toLocaleString('it-IT',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});restore.hidden=false;discard.hidden=false}}
 function save(){if(!currentUser||!document.getElementById('authOverlay').classList.contains('hidden'))return;const values={};for(const field of fields)values[field.id]=field.type==='checkbox'?field.checked:field.value;const draft={version:1,at:Date.now(),editing:spec.editing(),date:id==='evForm'?selectedDateKey:null,values};try{localStorage.setItem(workspaceDraftKey(id),JSON.stringify(draft));banner.hidden=false;banner.querySelector('span').textContent='Bozza conservata su questo dispositivo. Salva per inviarla al tuo account.';restore.hidden=true;discard.hidden=false}catch{banner.hidden=false;banner.querySelector('span').textContent='Impossibile conservare la bozza sul dispositivo. Salva prima di chiudere la pagina.';restore.hidden=true;discard.hidden=true}}
 form.addEventListener('input',save);form.addEventListener('change',save);
 restore.onclick=()=>{const draft=read();if(!draft)return;if(draft.editing){const item=spec.find(draft.editing);if(!item){banner.querySelector('span').textContent='La voce da modificare non è disponibile. Aggiorna i dati o elimina questa bozza.';return}if(id==='evForm'){const key=item.dateKey;const [y,m,d]=key.split('-').map(Number);viewYear=y;viewMonth=m-1;selectDay(key,d)}spec.edit(item)}else{spec.reset();if(id==='evForm'){if(!validCalendarDate(draft.date)){banner.querySelector('span').textContent='La bozza non ha una data valida. Seleziona un giorno e ricompilala.';return}const [y,m,d]=draft.date.split('-').map(Number);viewYear=y;viewMonth=m-1;selectDay(draft.date,d)}}for(const field of fields){const v=draft.values[field.id];if(field.type==='checkbox')field.checked=v===true;else if(typeof v==='string')field.value=v.slice(0,20000)}banner.querySelector('span').textContent='Bozza ripresa. Controlla i campi e salva nel tuo account.';restore.hidden=true;form.scrollIntoView({block:'center',behavior:'auto'});};
 discard.onclick=()=>{clearWorkspaceDraft(id);offer()};addEventListener('workspace:draft-cleared',e=>{if(e.detail===id)offer()});addEventListener('workspace:module',e=>{if(e.detail===spec.module)offer()});new MutationObserver(()=>{if(!document.getElementById('authOverlay').classList.contains('hidden'))banner.hidden=true;else offer()}).observe(document.getElementById('authOverlay'),{attributes:true,attributeFilter:['class']});offer();
 }
})();
