import {cartQuote,PayPalError,configured,DEMO_CATALOG,issueTicket,verifyTicket,requestId,paypalToken,paypalRequest,validateOrder,orderSummary,safeError} from '../_lib/paypal-sandbox.js';
export async function onRequestPost({request,env={}}){try{
 const origin=new URL(request.url).origin;if(request.headers.get('origin')&&request.headers.get('origin')!==origin)throw new PayPalError('Origine della richiesta non consentita.',403,'ORIGIN_MISMATCH');if(!request.headers.get('content-type')?.includes('application/json'))throw new PayPalError('Formato richiesta non valido.',415,'INVALID_BODY');const raw=await request.text();if(raw.length>5000)throw new PayPalError('Richiesta troppo grande.',413,'INVALID_BODY');let body;try{body=JSON.parse(raw)}catch{throw new PayPalError('JSON non valido.',400,'INVALID_BODY')}if(!['create','capture','status'].includes(body?.action))throw new PayPalError('Azione non valida.',400,'INVALID_ACTION');if(!configured(env))throw new PayPalError('Configura le credenziali PayPal Sandbox su Cloudflare.',503,'NOT_CONFIGURED');
 if(body.action==='create'){
  const product=cartQuote(body.items??body.product);if(!/^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/.test(body.attemptId||''))throw new PayPalError('Identificativo test non valido.',400,'INVALID_PRODUCT');
  const token=await paypalToken(env),idempotency=await requestId('create:'+origin+':'+body.attemptId+':'+JSON.stringify(product.selection));const payload={intent:'CAPTURE',purchase_units:[{reference_id:product.reference,description:product.name+' — SOLO TEST SANDBOX',amount:{currency_code:product.currency,value:product.value}}],payment_source:{paypal:{experience_context:{shipping_preference:'NO_SHIPPING',user_action:'PAY_NOW'}}}};
  let order=await paypalRequest(token,'/v2/checkout/orders','POST',payload,idempotency);if(!/^\w{8,32}$/.test(order.id||''))throw new PayPalError('Identificativo ordine PayPal non valido.');if(!order.purchase_units)order=await paypalRequest(token,'/v2/checkout/orders/'+order.id);validateOrder(order,product.selection,order.id);const ticket=await issueTicket({orderId:order.id,product:product.selection,origin,exp:Date.now()+3600000},env.PAYPAL_SANDBOX_CLIENT_SECRET);return Response.json({environment:'sandbox',orderId:order.id,ticket,amount:product.value,currency:product.currency},{headers:{'Cache-Control':'no-store'}})
 }
 const session=await verifyTicket(body.ticket,env.PAYPAL_SANDBOX_CLIENT_SECRET,origin);if(body.orderId!==session.orderId)throw new PayPalError('Ordine non corrispondente al test.',403,'INVALID_ORDER');const token=await paypalToken(env),path='/v2/checkout/orders/'+session.orderId;let order=await paypalRequest(token,path);validateOrder(order,session.product,session.orderId);
 if(body.action==='capture'&&order.status!=='COMPLETED'){
  if(order.status!=='APPROVED')throw new PayPalError('L’ordine deve essere approvato nel checkout prima della conferma.',409,'ORDER_NOT_APPROVED');
  await paypalRequest(token,path+'/capture','POST',{},await requestId('capture:'+session.orderId));order=await paypalRequest(token,path);
 }
 const summary=orderSummary(order,session.product,session.orderId);return Response.json(summary,{headers:{'Cache-Control':'no-store'}})
 }catch(error){return safeError(error)}}
