import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createOutfitFigure} from '../js/outfit-scene.js';import {parseNews,onRequestGet} from '../functions/api/football-news.js';import {publicProductUrl} from '../functions/api/fetch-product.js';
const c=vm.createContext({URL});vm.runInContext(await readFile(new URL('../js/outfit-data.js',import.meta.url),'utf8'),c);
test('Outfit data accepts only supported slots, shapes and public web references',()=>{const x=c.cleanOutfitItems({top:{shape:'script',color:'url(x)',title:'a'.repeat(300),url:'javascript:alert(1)',image:'https://shop.test/image.jpg'},evil:{shape:'coat'}});assert.equal(x.top.shape,'tshirt');assert.equal(x.top.color,'#e9dfcf');assert.equal(x.top.title.length,100);assert.equal(x.top.url,'');assert.equal(x.top.image,'https://shop.test/image.jpg');assert.equal(Object.keys(x).length,1);assert.equal(c.outfitWebUrl('https://user:password@example.com'),'')});
test('Saved outfit collection is bounded and malformed cloud data is tolerated',()=>{assert.equal(c.cleanSavedOutfits(null).length,0);assert.equal(c.cleanSavedOutfits([{},null]).length,0);const looks=c.cleanSavedOutfits(Array.from({length:30},(_,i)=>({id:String(i),name:'Look',items:{}})));assert.equal(looks.length,12)});
test('All selectable garment shapes produce finite 3D geometry and transforms',()=>{for(const [slot,shapes] of Object.entries(vm.runInContext('OUTFIT_SHAPES',c)))for(const shape of shapes){const f=createOutfitFigure({[slot]:{shape,color:'#345678'}});f.root.updateMatrixWorld(true);let garment=false;f.root.traverse(o=>{assert.ok(o.matrixWorld.elements.every(Number.isFinite));if(o.geometry){assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));if(o.material.color.getHexString()==='345678')garment=true}});assert.ok(garment);f.dispose()}});
test('RSS titles, sources and dates decode correctly without unsafe URLs',()=>{const xml='<rss><item><title><![CDATA[Una vittoria &amp; una festa]]></title><link>https://news.google.com/articles/one</link><pubDate>Mon, 14 Sep 2026 12:00:00 GMT</pubDate><source url="https://paper.test">Il giornale</source></item><item><title>Unsafe</title><link>javascript:alert(1)</link></item><item><title>Duplicate</title><link>https://news.google.com/articles/one</link></item></rss>';const x=parseNews(xml,'bologna');assert.equal(x.length,1);assert.equal(x[0].title,'Una vittoria & una festa');assert.equal(x[0].source,'Il giornale');assert.equal(x[0].publishedAt,'2026-09-14T12:00:00.000Z')});
test('News endpoint rejects arbitrary teams before fetching',async()=>{const r=await onRequestGet({request:new Request('https://app.test/api/football-news?team=https://private.test')});assert.equal(r.status,400)});
test('News feed failures are explicit and never create simulated articles',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('blocked',{status:403});try{const r=await onRequestGet({request:new Request('https://app.test/api/football-news?team=napoli')});assert.equal(r.status,502);assert.equal((await r.json()).articles,undefined)}finally{globalThis.fetch=original}});
test('News endpoint reads the fixed Google News feed and returns attributed articles',async()=>{const original=globalThis.fetch;let seen;globalThis.fetch=async url=>{seen=String(url);return new Response('<item><title>News</title><link>https://news.google.com/articles/a</link><source>Test publisher</source></item>')};try{const r=await onRequestGet({request:new Request('https://app.test/api/football-news?team=bologna')});assert.equal(r.status,200);assert.equal(new URL(seen).hostname,'news.google.com');assert.equal((await r.json()).articles[0].source,'Test publisher');assert.equal(r.headers.get('Cache-Control'),'public, max-age=300')}finally{globalThis.fetch=original}});
test('Product importer rejects private literal addresses and credentials, including redirect targets',()=>{for(const value of ['http://localhost/x','http://127.0.0.1/x','http://169.254.169.254/','http://[::1]/','http://2130706433/','https://user:pass@example.com','http://shop.local/','https://example.com:9000/'])assert.throws(()=>publicProductUrl(value));assert.equal(publicProductUrl('https://www.example.com/product').hostname,'www.example.com')});

test('Product photos are used as actual material textures on the mannequin',async()=>{const {Texture}=await import('../vendor/three.module.js');const texture=new Texture();const f=createOutfitFigure({shoes:{shape:'sneakers',color:'#112233'}},{shoes:texture});let textured=0;f.root.traverse(o=>{if(o.material?.map===texture){textured++;assert.equal(o.material.color.getHexString(),'ffffff')}});assert.ok(textured>=2);f.dispose();texture.dispose()});
test('Image proxy refuses local targets and non-image upstream content',async()=>{const {onRequestGet:handler}=await import('../functions/api/product-image.js');assert.equal((await handler({request:new Request('https://app.test/api/product-image?url=http://127.0.0.1/') })).status,400);const original=globalThis.fetch;globalThis.fetch=async()=>new Response('<html>blocked</html>',{headers:{'Content-Type':'text/html'}});try{const r=await handler({request:new Request('https://app.test/api/product-image?url=https://shop.example/photo')});assert.equal(r.status,502)}finally{globalThis.fetch=original}});
test('Image proxy passes allowed image bytes and type without rewriting them',async()=>{const {onRequestGet:handler}=await import('../functions/api/product-image.js');const original=globalThis.fetch;globalThis.fetch=async()=>new Response(new Uint8Array([137,80,78,71]),{headers:{'Content-Type':'image/png'}});try{const r=await handler({request:new Request('https://app.test/api/product-image?url=https://shop.example/photo.png')});assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'image/png');assert.deepEqual([...new Uint8Array(await r.arrayBuffer())],[137,80,78,71])}finally{globalThis.fetch=original}});
