import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const src=await readFile(new URL('../js/personalization.js',import.meta.url),'utf8');
function setup(){const storage=new Map();const c=vm.createContext({localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},document:{documentElement:{setAttribute(){},style:{setProperty(){}}}},window:{dispatchEvent(){}},CustomEvent:class{constructor(type,options){this.detail=options.detail}}});vm.runInContext(src,c);return c;}
test('Preferences from one account do not reach another account or the logged-out page',()=>{const c=setup();c.initializePersonalPreferences({id:'alice',user_metadata:{workspace_preferences:{theme:'dark',accent:'forest'}}});c.writePersonalPreference('theme','dark');c.initializePersonalPreferences({id:'bob',user_metadata:{}});assert.equal(c.readPersonalPreference('theme'),'light');c.initializePersonalPreferences({id:'alice',user_metadata:{}});assert.equal(c.readPersonalPreference('theme'),'dark');c.resetPersonalPreferences();assert.equal(c.readPersonalPreference('theme'),null)});
test('Only supported themes, colors and private start pages are accepted',()=>{const c=setup();for(const p of [null,{theme:'javascript:bad',accent:'__proto__',start:'contatti',motion:'bad'}])assert.equal(JSON.stringify(c.normalizedPreferences(p)),JSON.stringify({customColor:'#796037',quality:'auto',avatar:'monogram',bio:'',sections:'all',theme:'light',accent:'gold',motion:'active',start:'home'}))});

test('Profile preferences validate enum values and bound the biography',()=>{const c=setup();const p=c.normalizedPreferences({quality:'script',avatar:'__proto__',sections:'hidden',bio:'a'.repeat(900)});assert.equal(p.quality,'auto');assert.equal(p.avatar,'monogram');assert.equal(p.sections,'all');assert.equal(p.bio.length,160);const valid=c.normalizedPreferences({quality:'lite',sections:'essentials',avatar:'onyx'});assert.equal(valid.quality,'lite');assert.equal(valid.sections,'essentials');assert.equal(valid.avatar,'onyx')});

test('Custom accent text and button foregrounds keep readable contrast',()=>{const c=setup();for(const color of ['#ffffff','#000000','#ff00ff','#ffeeaa','#0033ff','#0abc12'])for(const dark of [false,true]){const text=c.readableAccent(color,dark),bg=dark?'#171715':'#f6f2ea',a=c.colorLuminance(text),b=c.colorLuminance(bg);assert.ok((Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5);const ink=c.colorLuminance(c.contrastText(color)),fill=c.colorLuminance(color);assert.ok((Math.max(ink,fill)+.05)/(Math.min(ink,fill)+.05)>=4.5)}});
test('Custom colors are validated and saved to the account namespace',()=>{const c=setup();assert.equal(c.normalizedPreferences({accent:'custom',customColor:'url(javascript:x)'}).customColor,'#796037');c.initializePersonalPreferences({id:'custom-user',user_metadata:{workspace_preferences:{accent:'custom',customColor:'#12abef'}}});assert.equal(c.readPersonalPreference('customColor'),'#12abef');c.initializePersonalPreferences({id:'other',user_metadata:{}});assert.equal(c.readPersonalPreference('customColor'),'#796037')});
