import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const c=vm.createContext({});vm.runInContext(await readFile(new URL('../js/wishlist-details.js',import.meta.url),'utf8'),c);
test('Existing notes survive opening and saving in the enhanced wishlist',()=>{for(const notes of ['Taglia M, per me','<script>example</script>','DV-WISHLIST/1\ninvalid']){const d=c.wishlistDetails(notes);assert.equal(d.notes,notes);assert.equal(c.wishlistDetails(c.packWishlistDetails(d)).notes,notes)}});
test('Wishlist details round trip through the existing notes column',()=>{const d={notes:'Cotone\n100%',size:'42',color:'Nero',priority:'high',purchased:true};assert.equal(JSON.stringify(c.wishlistDetails(c.packWishlistDetails(d))),JSON.stringify(d));assert.equal(c.wishlistDetails('DV-WISHLIST/1\nnull').notes,'DV-WISHLIST/1\nnull')});
test('Unknown wishlist fields cannot change supported values',()=>{const d=c.wishlistDetails('DV-WISHLIST/1\n'+JSON.stringify({notes:'',size:[],color:{},priority:'__proto__',purchased:'true'}));assert.equal(d.size,'');assert.equal(d.color,'');assert.equal(d.priority,'normal');assert.equal(d.purchased,false)});
const source=await readFile(new URL('../js/edition.js',import.meta.url),'utf8');
function removal(){let timer,undo,observer,removed=false;const auth={classList:{contains:()=>true}};const ctx=vm.createContext({currentUser:{id:'alice'},document:{getElementById:()=>auth,body:{append(){}},createElement:tag=>{const el={className:'',setAttribute(){},append(){},remove(){removed=true}};if(tag==='button')undo=el;return el}},MutationObserver:class{constructor(fn){observer=fn}observe(){}disconnect(){}},setTimeout:fn=>{timer=fn;return 1},clearTimeout(){},addEventListener(){},removeEventListener(){}});vm.runInContext(source.slice(source.indexOf('function confirmWishlistRemoval')),ctx);return {ctx,fire:()=>timer(),undo:()=>undo.onclick(),removed:()=>removed}}
test('Undo cancels deletion before a database request can occur',async()=>{const x=removal();const p=x.ctx.confirmWishlistRemoval({title:'Dress'});x.undo();assert.equal(await p,false);assert.equal(x.removed(),true)});
test('Pending deletion cannot carry over to another account',async()=>{const x=removal();const p=x.ctx.confirmWishlistRemoval({title:'Dress'});x.ctx.currentUser={id:'bob'};x.fire();assert.equal(await p,false)});
test('Deletion proceeds only after the grace period for the same account',async()=>{const x=removal();const p=x.ctx.confirmWishlistRemoval({title:'Dress'});x.fire();assert.equal(await p,true)});
