import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const utils=await readFile(new URL('../js/workspace-utils.js',import.meta.url),'utf8'),services=await readFile(new URL('../js/workspace-services.js',import.meta.url),'utf8');
function setup(){const storage=new Map(),c=vm.createContext({URL,Date,Map,currentUser:{id:'alice',user_metadata:{}},window:{addEventListener(){},dispatchEvent(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Event:class{},CustomEvent:class{},AUTH_ENDPOINT:'https://auth.test',normalizedPreferences:x=>x||{},cleanSavedOutfits:x=>Array.isArray(x)?x:[]});vm.runInContext(utils+'\n'+services,c);c.getCurrentUser=async()=>c.currentUser;return c}
test('Money accepts Italian amounts precisely and rejects malformed or negative values',()=>{const c=setup();for(const [s,n] of [['24,50',2450],['1.234,56',123456],['12.34',1234],['1.234',123400],[' € 3,20 ',320],['0',0],['0,10',10]])assert.equal(c.parseMoneyCents(s),n,s);for(const s of ['-1','NaN','Infinity','1e3','2,456','12.34,56','1,2,3',''])assert.equal(c.parseMoneyCents(s),null,s)});
test('Calendar dates reject invalid days and format using local calendar components',()=>{const c=setup();assert.equal(c.validCalendarDate('2026-02-29'),false);assert.equal(c.validCalendarDate('2024-02-29'),true);assert.equal(c.validCalendarDate('2026-13-02'),false);assert.equal(c.localCalendarDate({getFullYear:()=>2026,getMonth:()=>8,getDate:()=>15}),'2026-09-15')});
test('Monthly budget uses all month entries and exact cents, including over-budget states',()=>{const c=setup();const entries=[{expense_date:'2026-09-01',amount:.1},{expense_date:'2026-09-02',amount:.2},{expense_date:'2026-10-01',amount:100}];const s=c.budgetSnapshot(entries,'2026-09',25);assert.equal(s.spent,30);assert.equal(s.remaining,-5);assert.equal(s.percent,100);assert.equal(c.budgetSnapshot(entries,'2026-09',0).remaining,null)});
test('CSV escapes quotes, newlines and spreadsheet formula payloads',()=>{const c=setup();const csv=c.csvDocument([['=WEBSERVICE("bad")','+2','@SUM(A1)','a;b','a\nb','normal']]);assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.includes('"\'=WEBSERVICE(""bad"")"'));assert.ok(csv.includes('"a;b"'));assert.ok(csv.includes('"a\nb"'));assert.ok(csv.includes('"normal"'))});
test('Article saves cannot leak into a second account or guest session',async()=>{const c=setup();await c.toggleSavedArticle({url:'https://news.test/one',title:'Notizia',source:'Fonte',team:'bologna'});assert.equal(c.savedArticles().length,1);c.currentUser={id:'bob'};assert.equal(c.savedArticles().length,0);c.currentUser=null;assert.equal(c.savedArticles().length,0);await assert.rejects(c.toggleSavedArticle({}),/Accedi/);c.currentUser={id:'alice'};assert.equal(c.savedArticles()[0].title,'Notizia')});
test('Failed article storage is reported instead of claiming the article was saved',async()=>{const c=setup();c.localStorage.setItem=()=>{throw Error('quota')};await assert.rejects(c.toggleSavedArticle({url:'https://news.test/one',title:'Notizia',team:'napoli'}),/browser/);assert.equal(c.savedArticles().length,0)});
test('Bookmark normalization deduplicates links and rejects unsafe protocols',()=>{const c=setup();const p=c.cleanWorkspaceTools({articles:[{team:'bologna',title:'A',url:'javascript:bad'},{team:'napoli',title:'B',url:'https://news.test/'},{team:'napoli',title:'C',url:'https://news.test/'}],budgets:{'2026-09':25000,'2026-99':100,'2026-10':-1}});assert.equal(p.articles.length,1);assert.equal(Object.keys(p.budgets).length,1)});
test('Exports paginate until empty even when the server returns fewer than requested rows',async()=>{const c=setup();const seen=[];const pages=[[{id:1,user_id:'alice'}],[{id:2,user_id:'alice'}],[]];const rows=await c.fetchCompleteTable(async(path,options)=>{seen.push(path);assert.equal(options.cache,'no-store');return pages.shift()},'alice');assert.equal(rows.length,2);assert.ok(seen[2].includes('offset=2'))});
test('Exports stop on account changes and reject foreign-owned rows',async()=>{const c=setup();await assert.rejects(c.fetchCompleteTable(async()=>[{id:1,user_id:'bob'}],'alice'),/non appartenenti/);await assert.rejects(c.fetchCompleteTable(async()=>{c.currentUser={id:'bob'};return [{id:1,user_id:'alice'}]},'alice'),/account/)});
test('Complete backup includes all personal tables but never auth metadata or tokens',async()=>{const c=setup();const requests=['supabaseRequest','careerRequest','contactsRequest','wishlistRequest','expensesRequest'];for(const name of requests){let call=0;c[name]=async()=>call++===0?[{id:1,user_id:'alice'}]:[]}c.currentUser.user_metadata={full_name:'Alice',access_token:'SECRET',refresh_token:'SECRET2',workspace_preferences:{theme:'dark'},saved_outfits:[]};const backup=await c.exportPersonalBackup();assert.equal(Object.keys(backup.tables).length,5);assert.equal(backup.profile.full_name,'Alice');assert.ok(!JSON.stringify(backup).includes('SECRET'))});
test('A failed table prevents a partial file from being labelled a complete backup',async()=>{const c=setup();c.supabaseRequest=async()=>{throw Error('offline')};c.careerRequest=c.contactsRequest=c.wishlistRequest=c.expensesRequest=async()=>[];await assert.rejects(c.exportPersonalBackup(),/offline/)});
test('Queued budget saves preserve previous writes and do not carry into a different account',async()=>{const c=setup();let saved;c.authorizedFetch=async(url,options)=>{saved=JSON.parse(options.body).data.workspace_tools;return {ok:true,json:async()=>({id:'alice',user_metadata:{workspace_tools:saved}})}};await Promise.all([c.updateWorkspaceTools(data=>{data.budgets['2026-09']=10000;return data}),c.updateWorkspaceTools(data=>{data.budgets['2026-10']=20000;return data})]);assert.equal(saved.budgets['2026-09'],10000);assert.equal(saved.budgets['2026-10'],20000);const pending=c.updateWorkspaceTools(data=>data);c.currentUser={id:'bob'};await assert.rejects(pending,/Accedi/)});
